services:
  jekyll:
    image: ruby:3.3.5
    command: bash -c "gem install bundler:4.0.6 && bundle install && bundle exec jekyll serve --host 0.0.0.0 --baseurl /az_raihan --force_polling --livereload"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache:
